#!/bin/bash

#  Utilization `envsubst`  Place the template file in the ${NGINX_PORT}  Replace with the actual environment variable values
envsubst '${NGINX_PORT}${PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
#  Automatic update
if [ "${MOVIEPILOT_AUTO_UPDATE}" = "true" ]; then
    cd /
    /usr/local/bin/mp_update
    cd /app
else
    echo " Automatic program upgrades are turned off， For automatic upgrades set the environment variable when creating the container：MOVIEPILOT_AUTO_UPDATE=true"
fi
#  Variation moviepilot userid  Cap (a poem) groupid
groupmod -o -g ${PGID} moviepilot
usermod -o -u ${PUID} moviepilot
#  Changing file permissions
chown -R moviepilot:moviepilot \
    ${HOME} \
    /app \
    /public \
    /config \
    /var/lib/nginx \
    /var/log/nginx
chown moviepilot:moviepilot /etc/hosts /tmp
#  Download browser kernel
gosu moviepilot:moviepilot playwright install chromium
#  Launch front endnginx Service
nginx
#  Activate (a plan)haproxy
if [ -S "/var/run/docker.sock" ]; then
    haproxy -f /app/haproxy.cfg
fi
#  Setting the backend service privilege mask
umask ${UMASK}
#  Start the back-end service
exec dumb-init gosu moviepilot:moviepilot python3 app/main.py
