name:  Question feedback
description: File a bug report
title: "[ False]:  Please describe your problem briefly here"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please confirm the following information：
        1.  Please follow this template for submissionissues， Issues not submitted according to the template will simply be closed。
        2.  If your question can be directed to the previous issue  Or Telegram (television) channel  Hit the nail on the head， Then your issue  It will be shut down straight away.。
        3.  Be sure to describe the problem clearly when submitting a question、 Attached is the log， Problems that are poorly described and make it impossible to understand and analyze are simply shut down。
        4.  This warehouse is a back-end warehouse， If it's the front end WebUI  Questions can be answered at[ Front end repository](https://github.com/jxxghp/MoviePilot-Frontend) Carry (hanging down from the hand) issue。
  - type: checkboxes
    id: ensure
    attributes:
      label:  Recognize
      description:  In submitting issue  Beforehand， Please make sure you have read and acknowledge the following
      options:
        - label:  My version is the latest.， My version number is the same as the [version](https://github.com/jxxghp/MoviePilot/releases/latest)  Equal。
          required: true
        - label:  I have. [issue](https://github.com/jxxghp/MoviePilot/issues)  Searched in， Make sure my question hasn't been asked before。
          required: true
        - label:  I have. [Telegram (television) channel](https://t.me/moviepilot_channel)  Searched in， Make sure my question hasn't been asked before。
          required: true
        - label:  I've changed the title.， Change the title of the  Descriptive  Replace with the problem i'm having。
          required: true
  - type: input
    id: version
    attributes:
      label:  Current program version
      description:  The version number of the program at the time the problem was encountered
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label:  Type of problem
      description:  Which of the following sections have you encountered problems with
      options:
        -  Problems with the operation of the main program
        -  Plugin issues
        - Docker Or problems with the operating environment
        -  Other issues
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label:  Description of the problem
      description:  Please describe in detail the problem you encountered
      placeholder: " Description of the problem"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label:  System logs and configuration files in case of problems
      description:  When problems arise， Please copy the program runtime log here。
      render: bash
