blank_issues_enabled: false
contact_links:
  - name:  Item discussion
    url: https://github.com/jxxghp/MoviePilot/discussions/new/choose
    about: discussion
  - name: Telegram  (television) channel
    url: https://t.me/moviepilot_channel
    about:  Update log
  - name: Telegram  Communication group
    url: https://t.me/moviepilot_official
    about:  Exchange and mutual aid
