name:  Functionality improvement
description: Feature Request
title: "[Feature Request]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the features you would like to add。
  - type: input
    id: version
    attributes:
      label:  Current program version
      description:  Version of the program currently in use
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label:  Type of functional improvement
      description:  Which of the following areas do you need to improve functionality
      options:
        -  Main program
        -  Plug-in (software component)
        - Docker
        -  (sth. or sb) else
    validations:
      required: true
  - type: textarea
    id: feature-request
    attributes:
      label:  Functionality improvement
      description:  Please describe in detail the features that need to be improved or added。
      placeholder: " Functionality improvement"
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label:  Bibliography
      description:  Some references can be listed， But don't quote anything from similar but commercialized software。
      placeholder: " Bibliography"
