#  Configure the categorization strategy for movies，  Configure this item as empty or do not configure it to disable movie categorization.
movie:
  #  The category name is also the catalog name， Will match in order of precedence， The program creates a secondary directory by this name after the match is made
  Animated movie:
    #  Classification basis， Can be：original_language  Language type (in a classification)、production_countries  Country or area、genre_ids  Type of content, etc.， So long asTMDB API Returned fields are fine if they are
    #  When configuring multiple conditions， Needs to be satisfied at the same time； Unwanted matches can be deleted or configured as empty
    #  Match genre_ids  Content type，16 It's anime.
    genre_ids: '16'
  Chinese language movie:
    #  Matching languages
    original_language: 'zh,cn,bo,za'
  #  When no filter is configured， Then, in order of priority, those that don't fit into the above categories will be under this category， Recommended configuration at the very end
  Foreign language movies:

#  Configure the categorization strategy for tv series，  Configure this item to be empty or leave it blank to disable tv show categorization.
tv:
  #  The category name is also the catalog name， Will match in order of precedence， The program creates a secondary directory by this name after the match is made
  Cartoons and comics:
    #  Classification basis， Can be：original_language  Language type (in a classification)、origin_country  Country or area、genre_ids  Type of content, etc.， So long asTMDB API Returned fields are fine if they are
    #  When configuring multiple conditions， Needs to be satisfied at the same time； Unwanted matches can be deleted or configured as empty
    #  Match genre_ids  Content type，16 It's anime.
    genre_ids: '16'
  Documentary (film or tv program):
     #  Match genre_ids  Content type，99 It's a documentary.
    genre_ids: '99'
  Violence:
    #  Match genre_ids  Content type，10762 Children
    genre_ids: '10762'
  Comprehensive arts and entertainment:
    #  Match genre_ids  Content type，10764 10767 It's all about variety.
    genre_ids: '10764,10767'
  Nationalized drama:
    #  Match origin_country  Our country，CN Mainland china，TW It's from taiwan, china.，HK Hong kong, china
    origin_country: 'CN,TW,HK'
  European and american drama:
    #  Match origin_country  Our country， List of major european and american countries
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  Japanese-south korean drama:
    #  Match origin_country  Our country， List of major asian countries
    origin_country: 'JP,KP,KR,TH,IN,SG'
  #  No match for the above classification， Then name it uncategorized
  Uncategorized:


## genre_ids  Content type  Dictionaries， Note that some of the chinese and english are not the same
#	28	Action
#	12	Adventure
#	16	Animation
#	35	Comedy
#	80	Crime
#	99	Documentary
#	18	Drama
#	10751	Family
#	14	Fantasy
#	36	History
#	27	Horror
#	10402	Music
#	9648	Mystery
#	10749	Romance
#	878  Science Fiction
#	10770	TV Movie
#	53	Thriller
#	10752	War
#	37	Western
#	28	 Movements
#	12	 Take chances
#	16	 Anime
#	35	 Comedy
#	80	 Offense
#	99	 Record
#	18	 Plots
#	10751	 Household
#	14	 Fantastical
#	36	 Histories
#	27	 Frightening
#	10402	 Concert
#	9648	 Unapologetic
#	10749	 Romance
#	878	 Sci-fi
#	10770	 Tv movie
#	53	 Horror (movie)
#	10752	 Conflict
#	37	 Western part

## original_language  Language type (in a classification)  Dictionaries
#	af	 Afrikaans (language)
#	ar	 Arabic (language)
#	az	 Azerbaijani (language)
#	be	 Belgian (language)
#	bg	 Bulgarian (language)
#	ca	 Catalan (language)
#	cs	 Czech (language)
#	cy	 Welsh (language)
#	da	 Danish
#	de	 German (language)
#	dv	 Tiwié (language)
#	el	 Greek language
#	en	 English (language)
#	eo	 Esperanto
#	es	 Spanish language
#	et	 Estonian (language)
#	eu	 Basque (language)
#	fa	 Farsi
#	fi	 Finnish (language)
#	fo	 Faroese
#	fr	 French (language)
#	gl	 Galician (language)
#	gu	 Gujarati (language)
#	he	 Hebrew language
#	hi	 Hindi (language)
#	hr	 Croatian (language)
#	hu	 Hungarian language
#	hy	 Armenian (language)
#	id	 Indonesian language
#	is	 Icelandic (language)
#	it	 Italian (language)
#	ja	 Dictionary
#	ka	 Georgian (language)
#	kk	 Kazakh language
#	kn	 Canara language
#	ko	 Korean language
#	kok	 Konkani
#	ky	 Kyrgyz (language)
#	lt	 Lithuanian (language)
#	lv	 Latvian (language)
#	mi	 Maori language
#	mk	 Macedonian (language)
#	mn	 Mongolian language
#	mr	 Marathi language of west india
#	ms	 Malay
#	mt	 Maltese (language)
#	nb	 Norwegian( Berkermer (name))
#	nl	 Dutch (language)
#	ns	 Northern sotho
#	pa	 Punjabi (language)
#	pl	 Polish (language)
#	pt	 Portuguese (language)
#	qu	 Quechua
#	ro	 Romanian (language)
#	ru	 Russian (language)
#	sa	 Sanskrit
#	se	 North samoan
#	sk	 Slovak (language)
#	sl	 Slovenian (language)
#	sq	 Albanian (language)
#	sv	 Swedish (language)
#	sw	 Kiswahili
#	syr	 Syriac language (from syria)
#	ta	 Tamil language
#	te	 Telegu, the official language of andhra pradesh, india
#	th	 Thai (language)
#	tl	 Tagalog (language)
#	tn	 Tswana language
#	tr	 Turkish (language)
#	ts	 Zonga language
#	tt	 Tatar (language)
#	uk	 Ukrainian (language)
#	ur	 Urdu (language)
#	uz	 Uzbek (language)
#	vi	 Vietnamese language
#	xh	 Bantu language
#	zh	 Chinese writing
#	cn	 Chinese writing
#	zu	 Zulu (language)

## origin_country  Country area  Dictionaries
#	AR	 Argentina
#	AU	 Australia
#	BE	 Belgium
#	BR	 Brazilian
#	CA	 Canadian
#	CH	 Switzerland
#	CL	 Chile
#	CO	 Columbia (district of, or university etc)
#	CZ	 Czech republic (from 1993)
#	DE	 German
#	DK	 Denmark
#	EG	 Egypt
#	ES	 Spanish
#	FR	 French
#	GR	 Greece
#	HK	 Fact
#	IL	 Palestine
#	IN	 India
#	IQ	 Iraqi
#	IR	 Iranian
#	IT	 Italy
#	JP	 Japanese
#	MM	 Myanmar (or burma)
#	MO	 Aomen
#	MX	 Mexico
#	MY	 Malaysia
#	NL	 The netherlands
#	NO	 Norway
#	PH	 Philippine
#	PK	 Pakistan
#	PL	 Polish
#	RU	 Georgia
#	SE	 Sweden
#	SG	 Singaporean
#	TH	 Thailand
#	TR	 Istanbul
#	US	 United states of america
#	VN	 Vietnam
#	CN	 Sino  Mainland china (prc excluding hong kong and macau, but including islands such as hainan)
#	GB	 United kingdom of great britain and northern ireland
#	TW	 China-taiwan
#	NZ	 New zeeland
#	SA	 Saudi arabia
#	LA	 Laos
#	KP	 Korean joseon or chosun dynasty 1392-1910  North korea (esp. japanese usage)
#	KR	 South korea (republic of korea)  South korea (esp. north korean usage)
#	PT	 Portugal
#	MN	 Mongolia  Mongolia
